% 18103276
function y = foo(t)
syms x
piecewise_function1a = piecewise(x<-5,0,...
                               -5<=x<-4,1,...
                               -4<=x<-3,-1,...
                               -3<=x<0,0,...
                               0<=x<1,x,...
                               1<=x<3,(0.5*x)+0.5,...
                               3<=x<4,2,...
                               4<=x<6,(-2*x)+10,...
                               6<=x<7,(2*x)-14,...
                               x>=7,0);
y = subs(piecewise_function1a,x,t);


